# Generated by Django 5.1.5 on 2025-02-27 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="栏目名称")),
                ("description", models.TextField(blank=True, verbose_name="栏目描述")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "期刊栏目",
                "verbose_name_plural": "期刊栏目管理",
            },
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="论文标题")),
                ("abstract", models.TextField(verbose_name="摘要")),
                ("keywords", models.CharField(max_length=200, verbose_name="关键词")),
                (
                    "co_authors",
                    models.TextField(blank=True, verbose_name="共同作者信息"),
                ),
                (
                    "corresponding_author",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="通讯作者"
                    ),
                ),
                (
                    "corresponding_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="通讯作者邮箱"
                    ),
                ),
                (
                    "manuscript_file",
                    models.FileField(
                        upload_to="manuscripts/%Y/%m/", verbose_name="论文文件"
                    ),
                ),
                (
                    "cover_letter",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="cover_letters/%Y/%m/",
                        verbose_name="投稿信",
                    ),
                ),
                (
                    "supplementary_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="supplementary/%Y/%m/",
                        verbose_name="补充材料",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "草稿"),
                            ("SUBMITTED", "已投稿"),
                            ("INITIAL_CHECK", "初审中"),
                            ("UNDER_REVIEW", "审稿中"),
                            ("REVISION_REQUIRED", "需要修改"),
                            ("REJECTED", "已拒绝"),
                            ("ACCEPTED", "已接受"),
                            ("PUBLISHED", "已发表"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="论文状态",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="投稿时间"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="最后更新时间"),
                ),
                (
                    "editor_comments",
                    models.TextField(blank=True, verbose_name="编辑备注"),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(default=True, verbose_name="匿名评审"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_papers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="投稿作者",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submission.category",
                        verbose_name="所属栏目",
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edited_papers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="负责编辑",
                    ),
                ),
            ],
            options={
                "verbose_name": "论文",
                "verbose_name_plural": "论文管理",
            },
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volume", models.IntegerField(verbose_name="卷号")),
                ("number", models.IntegerField(verbose_name="期号")),
                ("year", models.IntegerField(verbose_name="年份")),
                ("publication_date", models.DateField(verbose_name="出版日期")),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="是否当前期"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="issue_covers/%Y/%m/",
                        verbose_name="封面图片",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="期刊描述")),
                (
                    "papers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="issues",
                        to="submission.paper",
                        verbose_name="收录论文",
                    ),
                ),
            ],
            options={
                "verbose_name": "期刊期次",
                "verbose_name_plural": "期刊期次管理",
            },
        ),
        migrations.CreateModel(
            name="Revision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(verbose_name="修改版本")),
                (
                    "manuscript_file",
                    models.FileField(
                        upload_to="revisions/%Y/%m/", verbose_name="修改后论文"
                    ),
                ),
                (
                    "cover_letter",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="revision_letters/%Y/%m/",
                        verbose_name="修改说明",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "response_to_reviewers",
                    models.TextField(blank=True, verbose_name="对审稿意见的回应"),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="submission.paper",
                        verbose_name="论文",
                    ),
                ),
            ],
            options={
                "verbose_name": "论文修改记录",
                "verbose_name_plural": "论文修改记录管理",
            },
        ),
    ]
