# Generated by Django 5.1.5 on 2025-02-27 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("submission", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待审核"),
                            ("ACCEPTED", "已接受审稿"),
                            ("DECLINED", "已拒绝审稿"),
                            ("IN_PROGRESS", "审稿中"),
                            ("COMPLETED", "已完成"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="审稿状态",
                    ),
                ),
                (
                    "invited_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="邀请时间"),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="接受邀请时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="截止日期"
                    ),
                ),
                (
                    "recommendation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ACCEPT", "接受"),
                            ("MINOR_REVISION", "小修改后接受"),
                            ("MAJOR_REVISION", "大修改后再审"),
                            ("REJECT", "拒绝"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="审稿建议",
                    ),
                ),
                (
                    "comments_to_editor",
                    models.TextField(blank=True, verbose_name="给编辑的评语"),
                ),
                (
                    "comments_to_author",
                    models.TextField(blank=True, verbose_name="给作者的评语"),
                ),
                (
                    "originality_score",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="创新性评分"
                    ),
                ),
                (
                    "quality_score",
                    models.IntegerField(blank=True, null=True, verbose_name="质量评分"),
                ),
                (
                    "significance_score",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="重要性评分"
                    ),
                ),
                (
                    "clarity_score",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="清晰度评分"
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="submission.paper",
                        verbose_name="论文",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审稿人",
                    ),
                ),
            ],
            options={
                "verbose_name": "审稿任务",
                "verbose_name_plural": "审稿任务管理",
            },
        ),
    ]
